### PR TITLE
Add lenses for protobuf messages

### LINKED ISSUE #9: Add Datastructures according to the protobuf specs, and their Lenses
We chose `protocol-buffers` and `hprotoc` in #1, now let’s put it to use!  We’ll also want to access them using lenses.

### PR DESCRIPTION
**Pull request by photm5**
Fixes #9.

I’m not sure about the documentation yet.  Do we want to explain everything in detail, duplicating https://github.com/ricochet-im/ricochet/blob/master/doc/protocol.md?

### CODE REVIEW

**Comment by froozen** [comment]
> Do we want to explain everything in detail, duplicating https://github.com/ricochet-im/ricochet/blob/master/doc/protocol.md?

That would be nice, imo. Please document them in **some** way though.

**Comment by photm5** [comment]
I’m ok with that.  However, I’d propose to do that in a different PR.  Issue #32 will act as a reminder.

**Comment by froozen** [comment]
I don't think putting undocumented code on master is good style. You should write haddock commets for all of the lenses you wrote.
Especially where you documented things in the module documentation instead of their actual implementation, as in `HasFeature` for example.

**Comment by photm5** [comment]
- I made haddock exclude the hproc-generated modules from the generated output. However, they’ll still show up in the “Haddock coverage” output, which is annoying.
- I added some more documentation to the `AuthHidenService` module.  Do you, @froozen, approve of the style and amount?  I didn’t add documentation to the types though, since we cannot just re-create them the way I did it with the lenses.

**Comment by froozen** [comment]
It's very good. I realy like it.
A little nitpick would be, that I think the textblocks in multiline haddock comments should be aligned like this:

``` haskell
-- | Some docs
--   that continue on the next line
```

**Comment by sternenseemann** [comment]
@froozen Please add this to CONTRIBUTING.adoc since nobody except for you has following this I think :)

**Comment by photm5** [comment]
What do you think about 15775e76bb6bd169b80552683fa15925d66ff956 and 8e1f806336c24e915fa45953a7be20a6654dd66f?

**Comment by froozen** [comment]
Both seem useful.

**Comment by photm5** [comment]
@froozen @lukasepple Are you both ok with merging this PR?

**Comment by froozen** [comment]
Yeah, it's very well documented, so it fullfills my final merge criterion. :+1:

**Comment by photm5** [comment]
@lukasepple Only you’re left :)

**Comment by sternenseemann** [comment]
Looks good to me.

**Comment by photm5** [comment]
Great!

**Pull request merged**
