### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by photm5**
These are some misc. changes, most importantly cleaning up the imports.

### CODE REVIEW

**Comment by sternenseemann** [comment]
Looks good, thanks for that! :+1:

**Comment by photm5** [comment]
Nice.  I’ll merge this as soon as you approve, @froozen.

**Comment by froozen** [comment]
Approved. :+1:
Would be nice if github had some sort of PR approval feature.

**Comment by photm5** [comment]
How about tags?  `approved-froozen`, etc.?

**Comment by sternenseemann** [comment]
Would work.

**Comment by photm5** [comment]
@froozen Did you think about the tags idea?

**Comment by froozen** [comment]
Tags as in github labels?

**Comment by photm5** [comment]
Yes.

**Pull request merged**
