### PR TITLE
Run hprotoc as preConf hook

### LINKED ISSUE #10: Include hprotoc in the build system
I tried to add a pre-config hook to `Setup.hs`, using this code:

``` haskell
import Distribution.Simple
import Data.Monoid((<>))

curry2 :: ((a -> b -> c) -> (a1 -> b1 -> c1) -> d) -> (((a, b) -> c) -> ((a1, b1) -> c1) -> d)
curry2 = flip (.) curry . flip . flip (.) curry . flip

combine' :: (Monad m, Monoid b) => (a -> m b) -> (a -> m b) -> (a -> m b)
combine' f g x = f x >>= \rf -> g x >>= \rg -> return $ rf <> rg

--combine :: (Monad m, Monoid c) => (a -> b -> m c) -> (a -> b -> m c) -> (a -> b -> m c)
--combine = uncurry . combine' . curry2

preConfHook = preConf simpleUserHooks `combine` const const (putStrLn "test")
main = defaultMainWithHooks $ simpleUserHooks { preConf = preConfHook }
```

Sadly, the commented out part doesn’t compile.

### PR DESCRIPTION
**Pull request by photm5**
Fixes #10.

### CODE REVIEW

**Comment by sternenseemann** [comment]
Is it merge-able?

**Comment by photm5** [comment]
I think so, but I’m not sure about the code quality.

**Comment by sternenseemann** [comment]
Well, you've come to a point where one could argue that you're doing obfuscation throught pointfree programming rather than making anything more readable. :)

**Comment by photm5** [comment]
Should I include comments that explain how I create `combine`? This seems a bit silly, as `Setup.hs` is the least important part of the whole codebase... So maybe I should’ve answered “Yes, it’s mergeable, as the code quality doesn’t matter.”.

**Comment by sternenseemann** [comment]
I guess, just merge, huh?

**Comment by photm5** [comment]
Well, yes :). Merging...

**Comment by sternenseemann** [comment]
Nice.

**Pull request closed without merging**
